set_property PACKAGE_PIN P20 [get_ports {rgmii_0_rd[3]}]
set_property PACKAGE_PIN P21 [get_ports {rgmii_0_rd[2]}]
set_property PACKAGE_PIN N18 [get_ports {rgmii_0_rd[1]}]
set_property PACKAGE_PIN J18 [get_ports {rgmii_0_rd[0]}]
set_property PACKAGE_PIN L21 [get_ports {rgmii_0_td[3]}]
set_property PACKAGE_PIN N17 [get_ports {rgmii_0_td[2]}]
set_property PACKAGE_PIN T17 [get_ports {rgmii_0_td[1]}]
set_property PACKAGE_PIN J22 [get_ports {rgmii_0_td[0]}]
set_property PACKAGE_PIN K18 [get_ports rgmii_0_rx_ctl]
set_property PACKAGE_PIN M19 [get_ports rgmii_0_rxc]
set_property PACKAGE_PIN J16 [get_ports rgmii_0_tx_ctl]
set_property PACKAGE_PIN J17 [get_ports rgmii_0_txc]
set_property PACKAGE_PIN L17 [get_ports {rgmii_1_rd[3]}]
set_property PACKAGE_PIN P17 [get_ports {rgmii_1_rd[2]}]
set_property PACKAGE_PIN M22 [get_ports {rgmii_1_rd[1]}]
set_property PACKAGE_PIN T16 [get_ports {rgmii_1_rd[0]}]
set_property PACKAGE_PIN T19 [get_ports {rgmii_1_td[3]}]
set_property PACKAGE_PIN M20 [get_ports {rgmii_1_td[2]}]
set_property PACKAGE_PIN P18 [get_ports {rgmii_1_td[1]}]
set_property PACKAGE_PIN N22 [get_ports {rgmii_1_td[0]}]
set_property PACKAGE_PIN R20 [get_ports rgmii_1_rx_ctl]
set_property PACKAGE_PIN N19 [get_ports rgmii_1_rxc]
set_property PACKAGE_PIN R19 [get_ports rgmii_1_tx_ctl]
set_property PACKAGE_PIN R21 [get_ports rgmii_1_txc]
set_property PACKAGE_PIN E21 [get_ports {rgmii_2_rd[3]}]
set_property PACKAGE_PIN G15 [get_ports {rgmii_2_rd[2]}]
set_property PACKAGE_PIN C20 [get_ports {rgmii_2_rd[1]}]
set_property PACKAGE_PIN E15 [get_ports {rgmii_2_rd[0]}]
set_property PACKAGE_PIN D21 [get_ports {rgmii_2_td[3]}]
set_property PACKAGE_PIN A18 [get_ports {rgmii_2_td[2]}]
set_property PACKAGE_PIN A17 [get_ports {rgmii_2_td[1]}]
set_property PACKAGE_PIN G21 [get_ports {rgmii_2_td[0]}]
set_property PACKAGE_PIN F18 [get_ports rgmii_2_rx_ctl]
set_property PACKAGE_PIN B19 [get_ports rgmii_2_rxc]
set_property PACKAGE_PIN E18 [get_ports rgmii_2_tx_ctl]
set_property PACKAGE_PIN C22 [get_ports rgmii_2_txc]
set_property PACKAGE_PIN C17 [get_ports {rgmii_3_rd[3]}]
set_property PACKAGE_PIN C18 [get_ports {rgmii_3_rd[2]}]
set_property PACKAGE_PIN A16 [get_ports {rgmii_3_rd[1]}]
set_property PACKAGE_PIN C15 [get_ports {rgmii_3_rd[0]}]
set_property PACKAGE_PIN G19 [get_ports {rgmii_3_td[3]}]
set_property PACKAGE_PIN G16 [get_ports {rgmii_3_td[2]}]
set_property PACKAGE_PIN E20 [get_ports {rgmii_3_td[1]}]
set_property PACKAGE_PIN F19 [get_ports {rgmii_3_td[0]}]
set_property PACKAGE_PIN A19 [get_ports rgmii_3_rx_ctl]
set_property PACKAGE_PIN D20 [get_ports rgmii_3_rxc]
set_property PACKAGE_PIN E19 [get_ports rgmii_3_tx_ctl]
set_property PACKAGE_PIN D22 [get_ports rgmii_3_txc]

set_property PACKAGE_PIN P22 [get_ports mdio_0_io]
set_property PACKAGE_PIN J21 [get_ports mdio_0_mdc]
set_property PACKAGE_PIN W20 [get_ports mdio_1_io]
set_property PACKAGE_PIN W21 [get_ports mdio_1_mdc]
set_property PACKAGE_PIN AA22 [get_ports mdio_2_io]
set_property PACKAGE_PIN AA21 [get_ports mdio_2_mdc]
set_property PACKAGE_PIN AB22 [get_ports mdio_3_io]
set_property PACKAGE_PIN AB21 [get_ports mdio_3_mdc]

set_property PULLUP true [get_ports mdio_0_io]
set_property PULLUP true [get_ports mdio_1_io]
set_property PULLUP true [get_ports mdio_2_io]
set_property PULLUP true [get_ports mdio_3_io]

set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_rd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_rd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_rd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_rd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_td[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_td[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_td[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_td[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_0_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_0_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_0_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_0_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_1_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_1_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_1_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_1_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_2_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_2_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_2_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_2_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_3_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_3_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_3_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_3_txc]

set_property IOSTANDARD LVCMOS25 [get_ports mdio_0_io]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_0_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_1_io]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_1_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_2_io]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_2_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_3_io]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_3_mdc]

set_property PACKAGE_PIN P16 [get_ports btn_rst_n]
set_property IOSTANDARD LVCMOS25 [get_ports btn_rst_n]

set_property PACKAGE_PIN B17 [get_ports phy_rst_n_0]
set_property IOSTANDARD LVCMOS25 [get_ports phy_rst_n_0]

set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_1]
set_false_path -from [get_clocks clk_fpga_2] -to [get_clocks clk_fpga_1]
set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_2]

#set_max_delay -from [get_cells {*rxdata_in_bus[?].rgmii_rx_data_in*} -hierarchical] -to [get_cells {*GMII_MII_RX_GEN/RXD_REG1_reg[?]*} -hierarchical] 2.200
#set_property IDELAY_VALUE 10 [get_cells {*rgmii_interface/delay_rgmii_rx*}]
#set_property IDELAY_VALUE 10 [get_cells {*rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance i_onetsw_1_wrapper/onetsw_1_i/axi_ethernet_0/eth_mac/inst
set_property IDELAY_VALUE 8 [get_cells {tri_mode_ethernet_mac_i/rgmii_interface/delay_rgmii_rx* tri_mode_ethernet_mac_i/rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 8 [get_cells {tri_mode_ethernet_mac_i/rgmii_interface/delay_rgmii_rx* tri_mode_ethernet_mac_i/rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 8 [get_cells {tri_mode_ethernet_mac_i/rgmii_interface/delay_rgmii_rx* tri_mode_ethernet_mac_i/rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 8 [get_cells {tri_mode_ethernet_mac_i/rgmii_interface/delay_rgmii_rx* tri_mode_ethernet_mac_i/rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance -quiet
current_instance i_onetsw_1_wrapper/onetsw_1_i/axi_ethernet_1/eth_mac/inst
set_property IDELAY_VALUE 6 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 6 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 6 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 6 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance -quiet
current_instance i_onetsw_1_wrapper/onetsw_1_i/axi_ethernet_2/eth_mac/inst
set_property IDELAY_VALUE 4 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 4 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 4 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 4 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
current_instance -quiet
current_instance i_onetsw_1_wrapper/onetsw_1_i/axi_ethernet_3/eth_mac/inst
set_property IDELAY_VALUE 4 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 4 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 4 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]
set_property IDELAY_VALUE 4 [get_cells {rgmii_interface/delay_rgmii_rx* rgmii_interface/rxdata_bus[*].delay_rgmii_rx*}]




